Project business_trips_project {
  database_type: 'PostgreSQL'
  Note: 'ER-model for business trips (Task 1)'
}

Table Branch {
  branch_id integer [primary key]
  city varchar(100)
}

Table Employee {
  employee_id integer [primary key]
  branch_id integer
}

Table Trip {
  trip_id integer [primary key]
  employee_id integer
  branch_id integer
  planned_start_date date
  fact_start_date date
  planned_end_date date
  fact_end_date date
  task text
  cancel_date date
}

Table Flight {
  flight_id integer [primary key]
  trip_id integer
  origin_city varchar(100)
  destination_city varchar(100)
  airline varchar(100)
  flight_number varchar(20)
  departure_datetime datetime
  ticket_price decimal(10,2)
}

Table Hotel {
  hotel_id integer [primary key]
  name varchar(100)
  address text
  city varchar(100)
  room_charge decimal(10,2)
}

Table Hotel_reservation {
  reservation_id integer [primary key]
  trip_id integer
  hotel_id integer
  checkin_date date
  checkout_date date
}

Ref: "Branch"."branch_id" < "Employee"."branch_id" // один филиал — много сотрудников

Ref: "Branch"."branch_id" < "Trip"."branch_id" // один филиал — много поездок из него

Ref: "Employee"."employee_id" < "Trip"."employee_id" // один сотрудник — много поездок

Ref: "Trip"."trip_id" < "Flight"."trip_id" // одна поездка — два рейса (вылет и прилёт)

Ref: "Trip"."trip_id" < "Hotel_reservation"."trip_id" // одна поездка — одно бронирование отеля

Ref: "Hotel"."hotel_id" < "Hotel_reservation"."hotel_id" // один отель — много бронирований (через Hotel_reservation)
